{
 "title": "Task_7",
 "time": { "from": "2023-07-06T11:56:17.736Z", "to": "2023-07-06T13:21:48.424Z" },
 "panels": [
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{device=\"sda\", instance=\"localhost:9100\"}[1m])"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{device=\"sda\", instance=\"localhost:9100\"}[1m])"
    }
   ]
  },
  {
   "title": "Total Memory GB",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"localhost:9100\"} / 1024 / 1024"
    }
   ]
  },
  {
   "title": "Current Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"localhost:9100\"} - node_memory_MemFree_bytes{instance=\"localhost:9100\"}) / node_memory_MemTotal_bytes{instance=\"localhost:9100\"}"
    }
   ]
  },
  {
   "title": "Free Space HDD in GB",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"localhost:9100\", mountpoint=\"/\"} / 1024 / 1024 / 1000"
    }
   ]
  },
  {
   "title": "Current CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (cpu)(irate(node_cpu_seconds_total{instance=\"localhost:9100\",mode=\"idle\"}[30m]))) * 100",
     "legendFormat": "core={{cpu}}"
    }
   ]
  }
 ]
}